[profile.default]
src = "."
out = "out"
libs = ["lib"]
script = "script"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.default.fmt]
line_length = 100
tab_width = 4
bracket_spacing = false

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]
